In [ ]:
import os 
print(os.getcwd())
import xgboost as xgb
from src.data.load_data import load_train_data
from sklearn import linear_model
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

c:\Users\Amna\Desktop\Projects\Fertilizer


In [19]:
X_train, y_train, X_val, y_val, preprocessor, target_encoder = load_train_data()

In [20]:
reg = linear_model.RidgeCV(alphas=np.logspace(-6, 6, 13))

reg.fit(X_train, y_train)
print("Best alpha:", reg.alpha_)
print("Validation score:", reg.score(X_val, y_val))
regpred = reg.predict(X_val)



from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

poly = PolynomialFeatures(degree=2)
scaler = StandardScaler()

poly_X_train = poly.fit_transform(X_train)
poly_X_train = scaler.fit_transform(poly_X_train)
poly_X_val = poly.transform(X_val)
poly_X_val = scaler.transform(poly_X_val)

polyreg = linear_model.RidgeCV(alphas=np.logspace(-6, 6, 13))
polyreg.fit(poly_X_train, y_train)
polyreg.score(poly_X_val, y_val)

print("Best alpha:", polyreg.alpha_)
print("Validation score:", polyreg.score(poly_X_val, y_val))


Best alpha: 1000.0
Validation score: 0.0009812309856156126
Best alpha: 100000.0
Validation score: 0.0016966647476447383


In [21]:
print(reg.predict(X_val).argmax(axis=1))
print(y_val.argmax(axis=1))


[0 1 3 ... 2 4 0]
[4 6 5 ... 0 0 4]


In [22]:
print(dir(target_encoder))
print("Classes:", target_encoder.classes_)
print("Feature names:", preprocessor.get_feature_names_out())

['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__str__', '__subclasshook__', '__weakref__', '_build_request_for_signature', '_check_X', '_check_get_feature_name_combiner', '_check_infrequent_enabled', '_compute_n_features_outs', '_compute_transformed_categories', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_drop_idx_after_grouping', '_fit', '_fit_infrequent_category_mapping', '_get_default_requests', '_get_doc_link', '_get_metadata_request', '_get_param_names', '_get_params_html', '_html_repr', '_identify_infrequent', '_infrequent_enabled', '_map_drop_idx_to_infrequent', '_map_infrequent_categories', '_n_features_ou

AttributeError: 'OneHotEncoder' object has no attribute 'classes_'

In [ ]:
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

pca = PCA(n_components=2)
X_r = pca.fit(poly_X_train).transform(X_train)

lda = LinearDiscriminantAnalysis(n_components=5)
X_r2 = lda.fit(poly_X_train, y_train).transform(poly_X_train)

# Percentage of variance explained for each components
print(
    "explained variance ratio (first two components): %s"
    % str(pca.explained_variance_ratio_)
)

plt.figure()
colors = ["navy", "turquoise", "darkorange", "blue", "green", "red", "yellow", "purple"]
lw = 2

for color, i, target_name in zip(colors, range(len(target_encoder.classes_)), target_encoder.classes_):
    plt.scatter(
        X_r[y_train == i, 0], X_r[y_train == i, 1], color=color, alpha=0.8, lw=lw, label=target_name
    )
plt.legend(loc="best", shadow=False, scatterpoints=1)
plt.title("PCA of IRIS dataset")

plt.figure()
for color, i, target_name in zip(colors, range(len(target_encoder.classes_)), target_encoder.classes_):
    plt.scatter(
        X_r2[y_train == i, 0], X_r2[y_train == i, 1], alpha=0.8, color=color, label=target_name
    )
plt.legend(loc="best", shadow=False, scatterpoints=1)
plt.title("LDA of IRIS dataset")

plt.show()

ValueError: n_components cannot be larger than min(n_features, n_classes - 1).

In [ ]:
print(range(len(target_encoder.classes_)))

In [ ]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='entropy', random_state=42, max_depth = 2)
clf = clf.fit(X_train, y_train)
clf.score(X_val, y_val)
print("Decision Tree score:", clf.score(X_val, y_val))
#from sklearn import svm
#svm_model = svm.SVC(kernel='rbf', random_state=42, verbose=1)
#svm_model.fit(X_train, y_train)


Decision Tree score: 0.15381333333333333


In [ ]:
clf.get_depth()

53

In [ ]:
#svm_model.score(X_val, y_val)
print("SVM Validation score:", svm_model.score(X_val, y_val))

In [ ]:
X_train

array([[ 0.62014424, -1.66056335, -0.5243208 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.36715147,  0.14457471,  1.59529582, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.11696817,  0.29500288,  0.83223384, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.37173227,  0.44543105,  1.00180317, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.36538013, -0.90842249, -0.86345946, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.12332031,  0.7462874 ,  1.42572649, ...,  0.        ,
         0.        ,  0.        ]], shape=(600000, 22))